FORMAT: 1A
HOST: https://api.artisans.io

# Artisans.io

## Wprowadzenie

Dokumentacja przedstawia listę dostępnych metod oraz wymaganych parametrów do usługi Artisans.io. Usługa ta, została stworzona wyłącznie w celach edukacyjnych, aby umożliwić naukę korzystania z REST API między innymi z platform iOS, HTML5 czy Android.

Obecnie usługa jest w trybie BETA i jest bezpłatna dla wszystkich zarejestowanych użytkowników.